### ISSUE TITLE
Text only applies to those unable to get into CS courses

### ISSUE THREAD

**Issue by williamstome** [ilangray/solvecs#10]
As a graduate student I have no problem getting into courses, but it's easy to see there's a problem. Unfortunately, your site enforces language that does not reflect my position. Please allow the option to write your own message / edit the message text.

**Comment by samueldaniel** [comment]
After you fill in your name, choose your year (grad student is an option), and input your major/area of study, the letter appears. The letter itself is in a contenteditable=true div, so just click the text and delete the whole thing and write your own letter!
